nohup python3 mcmc_ukf.py BE &
nohup python3 mcmc_ukf.py BG &
nohup python3 mcmc_ukf.py CZ &
nohup python3 mcmc_ukf.py DK &
nohup python3 mcmc_ukf.py DE &
nohup python3 mcmc_ukf.py IE &
nohup python3 mcmc_ukf.py EE &
nohup python3 mcmc_ukf.py EL &
nohup python3 mcmc_ukf.py ES &
nohup python3 mcmc_ukf.py FR &
nohup python3 mcmc_ukf.py HR &
nohup python3 mcmc_ukf.py IT &
nohup python3 mcmc_ukf.py CY &
nohup python3 mcmc_ukf.py LV &
nohup python3 mcmc_ukf.py LT &
nohup python3 mcmc_ukf.py LU &
nohup python3 mcmc_ukf.py HU &
nohup python3 mcmc_ukf.py MT &
nohup python3 mcmc_ukf.py NL &
nohup python3 mcmc_ukf.py AT &
nohup python3 mcmc_ukf.py PL &
nohup python3 mcmc_ukf.py PT &
nohup python3 mcmc_ukf.py RO &
nohup python3 mcmc_ukf.py SI &
nohup python3 mcmc_ukf.py SK &
nohup python3 mcmc_ukf.py FI &
nohup python3 mcmc_ukf.py SE &