python analyze_and_forecast.py BE &
python analyze_and_forecast.py BG &
python analyze_and_forecast.py CZ &
python analyze_and_forecast.py DK &
python analyze_and_forecast.py DE &
python analyze_and_forecast.py EE &
python analyze_and_forecast.py IE &
python analyze_and_forecast.py EL &
python analyze_and_forecast.py ES &
python analyze_and_forecast.py FR &
python analyze_and_forecast.py HR &
python analyze_and_forecast.py IT &
python analyze_and_forecast.py CY &
python analyze_and_forecast.py LV &
python analyze_and_forecast.py LT &
python analyze_and_forecast.py LU &
python analyze_and_forecast.py HU &
python analyze_and_forecast.py MT &
python analyze_and_forecast.py NL &
python analyze_and_forecast.py AT &
python analyze_and_forecast.py PL &
python analyze_and_forecast.py PT &
python analyze_and_forecast.py RO &
python analyze_and_forecast.py SI &
python analyze_and_forecast.py SK &
python analyze_and_forecast.py FI &
python analyze_and_forecast.py SE &
